# Generated by Django 3.0.3 on 2020-02-23 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('numero_dni', models.CharField(blank=True, max_length=8, null=True)),
                ('foto_imagen', models.ImageField(blank=True, max_length=8, null=True, upload_to='')),
                ('region', models.CharField(blank=True, max_length=25, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
