# Generated by Django 3.0.3 on 2020-02-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsable',
            name='foto_imagen',
        ),
    ]
