# Generated by Django 3.0.3 on 2020-02-21 23:46

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ubication', '0001_initial'),
        ('Afiliados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='distrito_afiliado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='provincia_afiliado', chained_model_field='provincia_distrito', on_delete=django.db.models.deletion.CASCADE, to='ubication.Distrito'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='organizacion_politica_region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region (opcional)'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='provincia_afiliado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region_afiliado', chained_model_field='region_provincia', on_delete=django.db.models.deletion.CASCADE, to='ubication.Provincia'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='region_afiliado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubication.Region'),
        ),
    ]
